name: Create Turso Database Branch For Dev
on:
  create:
    branches:
      - '**'
jobs:
  create_database:
    name: 'Create Database - Dev'
    runs-on: ubuntu-latest
    steps:
      - name: Create Database via Turso API
        shell: bash
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SANITIZED_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//; s/-$//')
          RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TURSO_DEV_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"name": "$SANITIZED_NAME", "group": "${{ secrets.TURSO_GROUP_NAME }}", "seed": {"type": "database", "name": "${{ secrets.TURSO_DEV_DATABASE_NAME }}"} }' \
            "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases")

          if [ $? -ne 0 ]; then
            echo "Create database API call failed"
            exit 1
          fi

          HOSTNAME=$(echo $RESPONSE | jq -r '.database.Hostname')
          if [ -z "$HOSTNAME" ]; then
            echo "Hostname not found in response"
            exit 1
          fi

          echo "hostname=$HOSTNAME" >> $GITHUB_ENV
      - name: Echo Hostname
        run: echo "The hostname is ${{ env.hostname }}"
