name: Delete Turso Database Branch For Dev
on: delete
jobs:
  create_database:
    name: 'Delete Database - Dev'
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Delete Database via Turso API
        shell: bash
        run: |
          BRANCH_NAME=${{ github.event.ref }}
          SANITIZED_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//; s/-$//')
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.TURSO_PLATFORM_API_KEY }}" \
            "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases/$SANITIZED_NAME"

          if [ $? -ne 0 ]; then
            echo "Delete database API call failed"
            exit 1
          fi

          echo "$SANITIZED_NAME database deleted"
