name: Delete Turso Database Branch For Dev
on:
  delete:
    branches:
      - '**'
jobs:
  create_database:
    name: 'Delete Database - Dev'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Database via Turso API
        shell: bash
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SANITIZED_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//; s/-$//')
          RESPONSE=$(curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.TURSO_DEV_API_TOKEN }}" \
            "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/$SANITIZED_NAME")

          if [ $? -ne 0 ]; then
            echo "Delete database API call failed"
            exit 1
          fi

          echo "$SANITIZED_NAME database deleted"
