name: Deploy Prod
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: emilpriver/geni@main
        name: Run migrations
        with:
          migrations_folder: "./migrations"
          wait_timeout: "30"
          migrations_table: "schema_migrations"
          database_url: ${{ secrets.TURSO_PROD_DB_URL }}
          database_token: ${{ secrets.TURSO_PROD_DB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}
      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.0.3
        env:
          # docker related envs
          IMAGE_PATH: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }}
          APP_VERSION: ${{ github.ref_name }}
          APP_NAME: ${{ secrets.DOCKER_REPOSITORY }}-dev
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          # mi related envs
          MICONFIG: ${{ secrets.MICONFIG }}
          PK: ${{ secrets.PK }}
          # server related envs
          APP_ENV: ${{ secrets.APP_ENV }}
          PORT: ${{ secrets.PORT_PROD }}
          INNER_PORT: ${{ secrets.INNER_PORT }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_PROD_DB_FULL_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          DONOTREPLY_EMAIL: ${{ secrets.DONOTREPLY_EMAIL }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          PGP_SYM_KEY: ${{ secrets.PGP_SYM_KEY }}
          PASS_ENCRYPT_ALGO: ${{ secrets.PASS_ENCRYPT_ALGO }}
          JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESST_TOKEN_SECRET }}
          JWT_ACCESS_TOKEN_TYPE: ${{ secrets.JWT_ACCESS_TOKEN_TYPE }}
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
          JWT_REFRESH_TOKEN_TYPE: ${{ secrets.JWT_REFRESH_TOKEN_TYPE }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_KEY }}
          envs: MICONFIG,PK,IMAGE_PATH,APP_NAME,APP_ENV,INNER_PORT,PORT,TURSO_DATABASE_URL,RESEND_API_KEY,DONOTREPLY_EMAIL,SERVER_URL,PGP_SYM_KEY,PASS_ENCRYPT_ALGO,JWT_ACCESS_TOKEN_SECRET,JWT_ACCESS_TOKEN_TYPE,JWT_REFRESH_TOKEN_SECRET,JWT_REFRESH_TOKEN_TYPE,JWT_ISSUER,APP_VERSION,DOCKER_USERNAME
          script: |
            echo "$MICONFIG" > .miconfig.yaml
            echo "$PK" > private.pem
            export PATH=$PATH:$HOME/go/bin
            mi bento order
            echo "APP_VERSION=$APP_VERSION" >> .env
            echo "TURSO_DATABASE_URL=$TURSO_DATABASE_URL" >> .env
            cat ~/docker-pat | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker image pull $IMAGE_PATH
            docker container stop $APP_NAME
            docker container rm $APP_NAME
            docker container run -d --name $APP_NAME -p $PORT:$INNER_PORT --env-file .env $IMAGE_PATH
            docker system prune -f
            rm .miconfig.yaml
            rm private.pem
            rm .env
