name: Run tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: http://localhost:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Turso CLI
        env:
          TURSO_INSTALL_SKIP_SIGNUP: true
        run: |
          curl -sSfL https://get.tur.so/install.sh | bash
          ~/.turso/turso dev -p 9000 &
          echo "$!"
      - name: emilpriver/geni
        uses: emilpriver/geni@v1.1.4
        with:
          database_url: ${{ env.DATABASE_URL }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Start tests
        run: |
          go test -v ./...
